# bun 이미지 사용
FROM oven/bun:latest

# 작업 디렉토리 설정
WORKDIR /src/app

# 애플리케이션 파일 복사
COPY package.json ./
COPY bun.lockb ./

# bun으로 의존성 설치
RUN bun install

COPY . .

# 앱 실행 포트 노출
EXPOSE 3000

# 애플리케이션 실행
CMD ["bun", "--bun", "run", "dev"]
